language: go

services:
  - docker

before_install:
  - docker pull victorrds/etebase
  - docker run -d -v $PWD/scripts:/etebase/scripts -e DEBUG=true -p 80:3735 victorrds/etebase ./scripts/testmode.sh
  - ./scripts/wait-for-it.sh localhost:80

go:
  - 1.14
  - 1.15
  - master

script:
  - go fmt ./...
  - go vet ./...
  - ETEBASE_TEST_HOST=localhost:80 go test -race ./... -v
